apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        version: v1.0.0
    spec:
      containers:
      - name: web-app
        image: deekshithsn/k8s-deployment-strategies
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: VERSION
          value: v1.0.0
      
---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  labels:
    app: web-app
spec:
  type: LoadBalancer
  #this is the one tells relationship btw pod and service
  ports:
  - name:  external
    port:  80 #service port & pod port should be same here
    targetPort: http #this should match pod definition label
    #nodePort: 30002 #this element optional,if we dont specify it will provision port btw 30000-32767
    #protocol: TCP  #this is default
  selector:
    app: web-app # if we give wrong name it wont fail,it waits for with the same name pod is available or not
    version: v1.0.0
