#lets say i have nginx pod to be deployed, i have pod.yml file
#what happens when i deployed. it pulls the image and it runs nginx process.
#####lets nginx is taking 60seconds so for this 60sec/100sec my pod status it should be "not ready",in this k8s should not consider application to serve.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      run: probe-demo
  template:
    metadata:
      labels:
        run: probe-demo
    spec:
      containers:
      - image: deekshithsn/probe-demo
        name: probe-demo
        env:
        - name: START_DELAY
          value: "100"        
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name:  probe-service
spec:
  selector:
    run:  probe-demo
  type:  NodePort
  ports:
  - name:  8080-8080
    port:  8080
    protocol: TCP
    targetPort:  8080
    nodeport: 30001
